# Site settings
title: federico castaneda
header-img: img/home-bg.jpg
email: castanedafederico@gmail.com
description: "Federico Castaneda's blog and stuff. "
url: http://federicocastaneda.github.io/ssp-sound/
baseurl: '/ssp-sound'
twitter_username: fedcastaneda
github_username:  federicocastaneda
facebook_username:  federicocastaneda

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
