# Site settings
timezone: America/New_York
title: ssp
header-img: img/home-bg.jpg
email: castanedafederico@gmail.com
description: "ssp prototype"
url: http://federicocastaneda.github.io/ssp-sound/
baseurl: '/ssp-sound'
github_project: ssp-sound

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
